In [3]:
import tensorflow as tf
import keras
model = tf.keras.models.load_model(r"D:\Projects\precipitation_AUS\models\CNN_RA_(3,3).keras")


In [5]:
model.layers

[<Conv1D name=conv1d_33, built=True>,
 <Conv1D name=conv1d_34, built=True>,
 <Flatten name=flatten_9, built=True>,
 <Dense name=dense_9, built=True>]

In [12]:
w = model.layers[0].get_weights()

In [13]:
len(w)


2

In [14]:
w[1].shape

(32,)

In [15]:
w[0].shape

(2, 6, 32)

In [19]:
l = model.layers


In [20]:
l0= l[0]

In [23]:
l0.weights[0]

<KerasVariable shape=(2, 6, 32), dtype=float32, path=conv1d_33/kernel>

In [26]:
keras.Variable( [ 1 , 2  , 3 ])

<KerasVariable shape=(3,), dtype=float32, path=variable_1>

In [27]:
l0.weights[0] = keras.Variable( [ 1 , 2  , 3 ])

In [33]:
import numpy as np

In [34]:
np.array(l0.weights[0])

array([[[-1.61851808e-01,  1.99268371e-01, -5.03376089e-02,
         -4.17364836e-02,  1.47961499e-02,  1.54177755e-01,
         -7.30257928e-02, -3.87596101e-01,  4.14184660e-01,
          3.16843748e-01,  1.17457174e-01,  6.00734679e-03,
          1.58801645e-01,  1.31620109e-01,  2.34124232e-02,
         -4.21539336e-01, -1.81091979e-01, -5.66595256e-01,
          4.29028571e-02,  1.02191210e-01, -1.13753669e-01,
         -1.88222621e-02,  4.57501672e-02, -3.83827388e-02,
          4.41130884e-02,  2.02706262e-01, -1.17261216e-01,
          1.01704210e-01,  9.14682150e-02, -1.11180820e-01,
         -2.85819978e-01,  4.30549048e-02],
        [ 7.99315423e-02,  7.14338794e-02, -7.30698854e-02,
          1.72969818e-01, -8.70129615e-02,  4.21412811e-02,
          1.41182855e-01,  1.99315503e-01, -5.24679907e-02,
         -1.99561238e-01,  5.66748306e-02, -3.99931893e-02,
         -4.89151804e-04, -6.63043112e-02, -1.17663695e-02,
          2.34100163e-01,  3.55227321e-01,  1.75721228e-

In [55]:
a= np.random.rand(2, 6, 32 )
b = np.random.rand( 32 )

In [46]:
a.shape

(6, 8, 4)

In [48]:
a

array([[[0.45392485, 0.94887564, 0.29980067, 0.56563744],
        [0.82711466, 0.71797127, 0.6048308 , 0.06180275],
        [0.39549237, 0.43937045, 0.4403295 , 0.93526316],
        [0.94174927, 0.750363  , 0.19064582, 0.69415128],
        [0.61263438, 0.09352197, 0.04040272, 0.80462511],
        [0.52826539, 0.05984914, 0.43378792, 0.7288367 ],
        [0.75584927, 0.64219148, 0.38001199, 0.72737323],
        [0.63199046, 0.87107391, 0.16709504, 0.8901606 ]],

       [[0.88159849, 0.57012516, 0.88491841, 0.2572517 ],
        [0.82852936, 0.84097314, 0.48424678, 0.90183655],
        [0.20069693, 0.10096859, 0.8469083 , 0.599173  ],
        [0.48487916, 0.9355409 , 0.29779932, 0.37787772],
        [0.89653341, 0.84089016, 0.92995563, 0.24235687],
        [0.5011538 , 0.32471653, 0.66934392, 0.84249128],
        [0.17126997, 0.57512156, 0.48243898, 0.60860436],
        [0.72382581, 0.81225044, 0.58672821, 0.69816523]],

       [[0.04913476, 0.94282392, 0.54344605, 0.81105071],
        [0

In [52]:
l0 = model.layers[0]

In [56]:
l0.set_weights( [a , b])

In [60]:
l0.get_weights()

[array([[[0.75678414, 0.89392585, 0.22398806, 0.8895746 , 0.19808428,
          0.4769824 , 0.06602025, 0.39955732, 0.8252159 , 0.4151335 ,
          0.9274652 , 0.89142174, 0.6928514 , 0.77816105, 0.737235  ,
          0.07824035, 0.38158128, 0.3541783 , 0.8683224 , 0.64145267,
          0.32244515, 0.46633095, 0.8269094 , 0.7931312 , 0.2793391 ,
          0.81284493, 0.03156216, 0.45313707, 0.6848581 , 0.00497012,
          0.6110543 , 0.80363244],
         [0.07154025, 0.35892496, 0.0798204 , 0.53262544, 0.31737363,
          0.60178685, 0.47292745, 0.62427175, 0.51321316, 0.3593448 ,
          0.25106138, 0.30699363, 0.82036614, 0.7462912 , 0.9738215 ,
          0.30870327, 0.75021225, 0.20410472, 0.32761678, 0.12614803,
          0.51730615, 0.53098756, 0.85486615, 0.21624486, 0.02268264,
          0.08095179, 0.65772414, 0.9208237 , 0.04796927, 0.0606126 ,
          0.35279584, 0.0444594 ],
         [0.7798964 , 0.7254637 , 0.2614549 , 0.34156534, 0.06419568,
          0.9812266 

In [62]:
model.layers[0].get_weights()

[array([[[0.75678414, 0.89392585, 0.22398806, 0.8895746 , 0.19808428,
          0.4769824 , 0.06602025, 0.39955732, 0.8252159 , 0.4151335 ,
          0.9274652 , 0.89142174, 0.6928514 , 0.77816105, 0.737235  ,
          0.07824035, 0.38158128, 0.3541783 , 0.8683224 , 0.64145267,
          0.32244515, 0.46633095, 0.8269094 , 0.7931312 , 0.2793391 ,
          0.81284493, 0.03156216, 0.45313707, 0.6848581 , 0.00497012,
          0.6110543 , 0.80363244],
         [0.07154025, 0.35892496, 0.0798204 , 0.53262544, 0.31737363,
          0.60178685, 0.47292745, 0.62427175, 0.51321316, 0.3593448 ,
          0.25106138, 0.30699363, 0.82036614, 0.7462912 , 0.9738215 ,
          0.30870327, 0.75021225, 0.20410472, 0.32761678, 0.12614803,
          0.51730615, 0.53098756, 0.85486615, 0.21624486, 0.02268264,
          0.08095179, 0.65772414, 0.9208237 , 0.04796927, 0.0606126 ,
          0.35279584, 0.0444594 ],
         [0.7798964 , 0.7254637 , 0.2614549 , 0.34156534, 0.06419568,
          0.9812266 

In [63]:
a

array([[[0.75678416, 0.89392582, 0.22398806, 0.88957456, 0.19808428,
         0.47698241, 0.06602025, 0.39955732, 0.82521585, 0.4151335 ,
         0.92746523, 0.89142173, 0.69285143, 0.77816107, 0.73723504,
         0.07824035, 0.38158129, 0.35417832, 0.86832238, 0.64145266,
         0.32244514, 0.46633094, 0.82690945, 0.79313116, 0.27933911,
         0.81284491, 0.03156216, 0.45313707, 0.6848581 , 0.00497012,
         0.6110543 , 0.80363246],
        [0.07154025, 0.35892495, 0.0798204 , 0.53262541, 0.31737362,
         0.60178686, 0.47292744, 0.62427176, 0.51321317, 0.35934482,
         0.25106139, 0.30699363, 0.82036616, 0.74629124, 0.9738215 ,
         0.30870327, 0.75021223, 0.20410473, 0.32761679, 0.12614803,
         0.51730615, 0.53098757, 0.85486616, 0.21624486, 0.02268264,
         0.0809518 , 0.65772415, 0.92082371, 0.04796927, 0.0606126 ,
         0.35279584, 0.0444594 ],
        [0.77989641, 0.72546369, 0.2614549 , 0.34156534, 0.06419568,
         0.98122664, 0.09067022, 0.